### ISSUE TITLE
Favicon bug

### ISSUE THREAD

**Issue by varshini-prakash** [WeilonYing/html5-music-player#1]
"GET /favicon.ico HTTP/1.1" 404 -
-bash: GET /favicon.ico HTTP/1.1: No such file or directory

Can you explain how to fix this?

**Comment by WeilonYing** [comment]
A [favicon](https://en.wikipedia.org/wiki/Favicon) doesn't exist in your setup. If you'd like to add a favicon, try following the instructions here: http://flask.pocoo.org/docs/0.12/patterns/favicon/
